server:
  port: 8200

spring:
  application:
    name: hello-service
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/